CREATE DATABASE ATLETICOS
    DEFAULT CHARACTER SET = 'utf8mb4';
    USE ATLETICOS;

CREATE TABLE USUARIO(
    ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
    P_NOMBRE VARCHAR(30) NOT NULL,
    S_NOMBRE VARCHAR(30) NULL,
    P_APELLIDO VARCHAR(30) NOT NULL,
    s_APELLIDO VARCHAR(30) NULL,
    GENERO CHAR(10) NOT NULL, 
    FECHA_NACIMIENTO DATE NOT NULL,
    FECHA_CREACION DATE NOT NULL,
    NIT_USUARIO VARCHAR(120) NOT NULL,
    CLAVE VARCHAR(20) NOT NULL
);

CREATE TABLE CELULAR(
    ID_CELULAR INT AUTO_INCREMENT PRIMARY KEY NOT NULL, 
    CELULAR VARCHAR(30) NOT NULL,
    FECHA_CREADO VARCHAR(30),
    ID_USUARIO_KF INT NOT NULL, 
    FOREIGN KEY(ID_USUARIO_KF) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE CORREO(
    ID_CORREO INT AUTO_INCREMENT PRIMARY KEY NOT NULL, 
    CORREO VARCHAR(30) NOT NULL,
    FECHA_CREADO VARCHAR(30),
    ID_USUARIO_KF INT NOT NULL, 
    FOREIGN KEY(ID_USUARIO_KF) REFERENCES USUARIO(ID_USUARIO)
);